server:
  port: 12306

spring:
  application:
    name: capol-workflow-server

  profiles:
    active: local

  cloud:
    consul:
      host: 10.1.207.24
      port: 8500
      enable: true
      discovery:
        enabled: true
        instance-id: ${spring.application.name}
        service-name: ${spring.application.name}

